### ISSUE TITLE
Multiple values?

### ISSUE THREAD

**Issue by zeshanshani** [simeydotme/donutty#14]
Hey there,

Can one chart have multiple values? Like this: [screenshot](https://s.zeshanahmed.com/Screenshot_12_11_2019__3_45_PM_237AC4C3.png)

Thanks!

**Comment by simeydotme** [comment]
Sorry @zeshanshani  that was never in the plan, as it's quite limited with the current way the chart works. I'd suggest a full charting library for that kind of thing :)

**Comment by zeshanshani** [comment]
@simeydotme thanks for your response. No worries. I thought so.
