### ISSUE TITLE
truncated container in Firefox

### ISSUE THREAD

**Issue by ghost** [simeydotme/donutty#15]
donut display is chopped on left and right, in Firefox. I'm unable to see where this is controlled. 

<img width="269" alt="image" src="https://user-images.githubusercontent.com/49204728/71853322-3a548000-3098-11ea-8e4b-1d6aea970880.png">

**Comment by simeydotme** [comment]
hi @dherboldswca ... I think this must be related to `preserveAspectRatio`, I recently added code to try and resolve this ... could you please create a codepen/jsfiddle to demonstrate, and tell me which version of FireFox & Donutty you're running :)
