### ISSUE TITLE
can you add the option for direction from right to left ?

### ISSUE THREAD

**Issue by t-sajid** [simeydotme/donutty#18]
clockwise direction option 

right now the pie chart is start from left to right can you add the option to show circle from right to left please .

![image](https://user-images.githubusercontent.com/65234843/87911201-a7ec5a80-ca84-11ea-80a4-3b80831b41b2.png)

**Comment by simeydotme** [comment]
ohhh, i can look in to that :)

**Comment by simeydotme** [comment]
done in [2.1.0](https://github.com/simeydotme/donutty/compare/2.0.0...2.1.0#diff-e33a23a92ea880016e9f49664c27798b1fc6de0f9e6d9b3caed3f23194bc1fac) by using a transform when `dir="rtl"` is detected on the wrapper, or `<html>` element
