### ISSUE TITLE
Make SVG accessible

### ISSUE THREAD

**Issue by viktorix** [simeydotme/donutty#19]
Hey, thanks for creating Donutty. Really helpful.

I just wanted to bring this to your attention. It would be great if SVGs were accessible. Here's a l[ink to making inline SVGs accessible](https://css-tricks.com/accessible-svgs/#2-inline-svg).

Basically, it would be helpful if there was another option "title" which would be added inside SVG as the first child of its parent as a `<title>` tag with a unique ID. Then, `<svg>` would also get `aria-labelledby` with the unique ID and also `role="img"`.

Although not necessary, it would also be helpful if `<desc>` was added too. The article explains all of this.

Thanks a lot!

**Comment by simeydotme** [comment]
Thanks for this suggestion!
I really want to accommodate this, will get to it at the next possible time

**Comment by viktorix** [comment]
Thanks.

**Comment by simeydotme** [comment]
let me know how this goes for you :)
it was a bit of a pain, but I added the ability to customise the `<title>` and `<desc>` or just use a default one in [2.2.0](https://github.com/simeydotme/donutty/compare/2.1.0...2.2.0#diff-e33a23a92ea880016e9f49664c27798b1fc6de0f9e6d9b3caed3f23194bc1fac)
