### ISSUE TITLE
Weird SVG display issues in Firefox

### ISSUE THREAD

**Issue by shanomurphy** [simeydotme/donutty#27]
Just thought I'd document some strange display issues on Firefox I ran into. The SVG donut wasn't displaying properly (like it was not fully rendering or being clipped).

Screen recording:

![firefox](https://user-images.githubusercontent.com/2593333/130857205-e4346d65-f0d8-417f-aa54-787df9944f94.gif)

Issue found in Firefox 91, worked ok in other browsers I tested.

It seems related to the `transform` attribute on the SVG element.

Overriding the transform attribute by setting `transform: scale(1)` on the svg (via my CSS) fixed the issue. Strangely setting `transform: none` didn't work.

P.s I was able to replicate the issue somewhat in the [codepen demo](https://codepen.io/simeydotme/pen/rrOEmO/) (didn't occur as often or as badly):

![image](https://user-images.githubusercontent.com/2593333/130858546-3278269c-8b92-4d7d-90de-3523239faa38.png)

**Comment by shanomurphy** [comment]
Hi, No, no viewport scaling or zoom. I've made a reduced test case:

https://jsfiddle.net/34bpcsex/

Upon further testing though I can confirm it's related to the `rotate` angle.

Any rotate angle that causes the svg box sides to be not parallel with the viewport causes the funkiness.
 
So the rotate angle of 93.333… causes problems:

![image](https://user-images.githubusercontent.com/2593333/131226029-50d9a285-a2a7-4153-ba01-dc8ca14c2243.png)

But an angle of `90deg` works perfectly fine:

![image](https://user-images.githubusercontent.com/2593333/131226061-8894f8e7-7c08-4829-8767-a1440d3189dd.png)

I'm guessing the `93.333…` is to try and offset the rounded ends?

Also can confirm I only noticed the issue when I was forced to use a very old device (2010 iMac). I've since tested on my usual computer using Firefox 91 and there are no apparent issues. So maybe it's hardware related somehow?

**Comment by shanomurphy** [comment]
Ok so looks like this old device has issues with rotated SVGs in Firefox (I just tested rotating various SVGs). So this doesn't look to be a code issue here. Thanks for your help!

**Comment by simeydotme** [comment]
**Wow, your first screenshot looks like a rasterization render-engine issue...** I run in to those a lot, on firefox, when doing filters, blend-mode and transforms as the browser attempts to render objects in to a new raster layer. That would account for why a non-rotated, or 90d rotated, doesn't show up as it doesn't have to place in a off-grid paint frame? not sure.. And the 2010 mac may have a very old graphics card with poor compatibility?

https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome
^^ here's some *cough "light reading" if you're interested :)

Yikes, but thanks for the diligent investigation!
