### ISSUE TITLE
 Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by i1group** [simeydotme/donutty#3]
When using `donutty.js` (without jquery) any attempt to initialize donutty will throw an error:
> Uncaught TypeError: Cannot read property 'style' of undefined
>     at win.Donutty.donutty.animate (donutty.js:235)
>     at win.Donutty.donutty.insertFragments (donutty.js:186)
>     at win.Donutty.donutty.init (donutty.js:78)
>     at new win.Donutty (donutty.js:59)
>     at donutty.js:348
>     at NodeList.forEach (<anonymous>)
>     at HTMLDocument.initialise (donutty.js:345)

Even very basic example `<div data-donutty></div>` will fail.

It's related to the `text` option, which is always `false` somehow in that script.
Could that be fixed? You may have a look at my fixed version of donutty.js here: https://www.diffchecker.com/gi42wjgz

**Comment by simeydotme** [comment]
Hey , thanks @i1group :)

The diff looks OK ... if you want to submit a PR and produce a simple before/after example in JSFiddle, then I'd be more than happy to include the changes and push a release ... if you're not able/confident then please bare with me and I'll get around to this in time.

Thanks, Si.

**Comment by i1group** [comment]
Before: https://codepen.io/i1group/pen/OYbXdp
After: https://codepen.io/i1group/pen/pmEYow
And PR is waiting for approval.
