### ISSUE TITLE
safari rotate bug

### ISSUE THREAD

**Issue by kukac7** [simeydotme/donutty#31]
in safari, svg's are rotated.
in chrome ok.

each is the latest version.

![Screenshot 2021-12-03 at 22 39 39](https://user-images.githubusercontent.com/1240104/144676204-c944e024-a784-4eb4-ad37-c805b5d625b6.png)

**Comment by simeydotme** [comment]
oh thanks, @kukac7 !

Any idea what the problem is? looks like a transform issue from a distance.. I don't have a Mac/Safari to test on right now, will check it next week.

**Comment by kukac7** [comment]
@simeydotme #32
