### ISSUE TITLE
How to add gradient color?

### ISSUE THREAD

**Issue by bdthemes** [simeydotme/donutty#33]
Is it possible to add gradient color support for the progress bar?

**Comment by simeydotme** [comment]
hmmm, @bdthemes  ... not totally sure.
Let me look into it, but it's not going to be a high priority.

If you have a code example, or a patch you want to submit for review, please go ahead.

**Comment by simeydotme** [comment]
I took a look, and it appears that cannot simply apply gradients on to Stroke for SVG.
If you are familiar/skilled in CSS you may be able to apply a "gradient filter" over the chart by;

- create a DIV
- position it absolutely over the chart with css
- apply an "multiply" blend mode in css
- apply your conic-gradient in css
- set the color of the donut to be mid-grey

**Comment by simeydotme** [comment]
Here's an example;

https://codepen.io/simeydotme/pen/wvPBJee

![image](https://user-images.githubusercontent.com/2817396/151233233-5082bbee-db79-4c94-9821-9e4fc18ccd68.png)
